name: remote ssh command
on: workflow_dispatch
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:        
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
#         timeout: 1200s
#         command_timeout: 20m
        script: whoami
