# This is a basic workflow to help you get started with Actions

name: test secret

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST1: ${{ secrets.TEST1 }}

    steps:
    - uses: actions/checkout@v2
    - run: echo $TEST1
